# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3323a6cfda3a8a07272149c03af854dc6e1ce5dcf585a313b87466b1f48127869ae40264ccc18dca68d93db606cd0a2661961fbf93f82d7a033c237f7c89e24f

test:
  secret_key_base: 5868b9d86b4bdca20c1cc0c42b28b5f39c974282fbcc907881c9717b76f487e32285b894abfa941edc2c3d75f8a5315756f3c775a36fa3f920e30142e93a9281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
